apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-peo6
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/devfile-sample-python-basic-peo6@sha256:842008fab384c72e49d8ab63d5aace5a8082339ad722c6e938cbfa485d102965
        name: my-python
        resources: {}
status: {}
